/* Paramind — TST Trainer patient bank.
   Kept out of the page source and cached by the browser (fetched once, reused). */
window.TST_DATA = [
  {id:"tp3a",pri:"P3",desc:"A man in his 50s is walking toward you. He's cradling his right arm and makes eye contact. No obvious bleeding."},
  {id:"tp3b",pri:"P3",desc:"A woman in her 30s is walking away from the incident, limping on her right leg. She's upright and mobile, clutching her shoulder. No major bleeding visible."},
  {id:"tp3c",pri:"P3",desc:"A teenage girl is walking fast toward you, crying. There is a small cut on her forehead. She is looking around in distress but making steady progress on her feet."},
  {id:"tb1a",pri:"P1",desc:"A woman in her 30s is on the ground, not moving. There is bright red, pulsatile bleeding from her left thigh. Her clothing is soaked."},
  {id:"tb1b",pri:"P1",desc:"A man in his 40s is slumped and unresponsive. His right forearm has a compound fracture with bone visible and bright red blood pooling rapidly beneath him."},
  {id:"tb1c",pri:"P1",desc:"A man in his 50s is on the ground. There is a large scalp laceration pouring blood — dark red, soaking his collar and the ground beneath his head."},
  {id:"tp2a",pri:"P2",desc:"A teenager, perhaps 16, is sitting down, talking loudly. She is crying and on her phone. No visible wounds. No blood."},
  {id:"tp2b",pri:"P2",desc:"A man in his 30s is sitting against a wall. He's talking — telling you his back hurts and he can't stand. No blood visible. No obvious external wounds."},
  {id:"tp2c",pri:"P2",desc:"A woman in her 40s is sitting on the ground, alert. She's speaking clearly — telling you she has chest pain and can't get up. No external bleeding or wounds visible."},
  {id:"tp4a",pri:"P1",desc:"A male driver in his late 40s is conscious and talking. He says he can't move his legs. There is a steering column fragment embedded in his left chest."},
  {id:"tp4b",pri:"P1",desc:"A woman in her 20s is conscious and talking clearly. She says she can't move her left leg. A metal shard protrudes from her right shoulder close to the base of the neck."},
  {id:"tp4c",pri:"P1",desc:"A woman in her 40s is conscious and talking. She says she felt something go into her side during the incident. An object is visible protruding from her left flank."},
  {id:"tp5a",pri:"P1",desc:"A woman in her 40s is lying down, eyes closed, not responding to your voice. No obvious bleeding. She is not breathing. You open her airway — she takes a breath."},
  {id:"tp5b",pri:"P1",desc:"A man in his 30s is face down. Unresponsive to loud shouting. No blood visible. No breathing. You open his airway — chest rise becomes visible two seconds later."},
  {id:"tp5c",pri:"P1",desc:"A man in his 20s is supine. Unconscious. No bleeding visible. No respiratory effort. You open his airway and tilt his head — shallow breathing begins within seconds."},
  {id:"td6a",pri:"DEAD",desc:"A male passenger in his 60s is lying supine. Eyes closed. No response to shouting. No visible haemorrhage. You open his airway — no breathing. No movement."},
  {id:"td6b",pri:"DEAD",desc:"An elderly woman is lying on the ground. Eyes closed. No response to voice or pain stimulus. No bleeding. You open her airway carefully — no chest movement. No breath sounds."},
  {id:"td6c",pri:"DEAD",desc:"A woman in her 30s is lying flat. No breathing visible. Unresponsive to all stimuli. No bleeding. You open her airway — no movement, no breath sounds detected."}
,
  {id:"tp3d",pri:"P3",desc:"A man in his 60s is walking toward you, holding a grazed forearm. He is steady on his feet and asks if he can sit down somewhere."},
  {id:"tp3e",pri:"P3",desc:"A woman in her 20s is walking away from the scene, coughing from the dust. She is upright, mobile and waving to you that she is okay."},
  {id:"tp3f",pri:"P3",desc:"A teenage boy walks over cradling his right wrist. He is talking, alert and moving freely on his feet."},
  {id:"tp3g",pri:"P3",desc:"A man in his 40s is limping clear of the wreckage. His trousers are torn over a superficial knee graze, but he is walking unaided."},
  {id:"tp3h",pri:"P3",desc:"A woman in her 70s is walking slowly alongside a railing. She is shaken, with a small cut to her cheek, but mobile and talking."},
  {id:"tp3i",pri:"P3",desc:"A man in his 30s is on his feet, pressing a cloth to a minor scalp graze. He is alert and walking toward the rendezvous point."},
  {id:"tp3j",pri:"P3",desc:"A woman in her 30s walks toward you carrying her bag, upright and steady. There is a graze across one cheek and nothing more obvious."},
  {id:"tp3k",pri:"P3",desc:"A man in his 50s is wandering off the carriageway, dazed but mobile. He is talking and has no visible bleeding."},
  {id:"tp3l",pri:"P3",desc:"A woman in her 40s is on her feet, holding her ribs and wincing. She is walking slowly and able to answer you."},
  {id:"tp2d",pri:"P2",desc:"A man in his 60s is sitting on the kerb. He is talking clearly but says his legs will not hold him. No blood is visible."},
  {id:"tp2e",pri:"P2",desc:"A woman in her 50s is lying on the ground, talking. She says her hip is too painful to stand on. No bleeding or wounds are visible."},
  {id:"tp2f",pri:"P2",desc:"A man in his 20s is sitting against the railings, winded and talking. There are no visible wounds and no bleeding."},
  {id:"tp2g",pri:"P2",desc:"A woman in her 30s is on the ground, alert and talking. She is holding her ankle and cannot weight-bear. No external bleeding."},
  {id:"tp2h",pri:"P2",desc:"An elderly man is seated, talking to a bystander. He is breathless but has no external injury and no bleeding."},
  {id:"tp2i",pri:"P2",desc:"A teenage girl is sitting down, crying and talking. She says her shoulder is hurting. There is no blood and no obvious wound."},
  {id:"tp2j",pri:"P2",desc:"A man in his 40s is lying on his side, talking, complaining of stomach pain. There is no external bleeding and no penetrating wound."},
  {id:"tb1d",pri:"P1",desc:"A man in his 30s is on the ground, not moving. Bright red blood is spurting from a wound to his upper arm and the ground is soaked."},
  {id:"tb1e",pri:"P1",desc:"A woman in her 50s has collapsed. Heavy dark blood is pumping from a wound high in her groin, saturating her clothing."},
  {id:"tb1f",pri:"P1",desc:"A man in his 60s is on the ground with a partial amputation below the knee. Bright blood is pooling rapidly beneath the limb."},
  {id:"tp4d",pri:"P1",desc:"A man in his 40s is conscious and talking. He says he cannot feel his legs. A shard of glass is embedded deep in his upper chest."},
  {id:"tp4e",pri:"P1",desc:"A woman in her 30s is conscious and talking. A length of metal rod is protruding from her abdomen."},
  {id:"tp4f",pri:"P1",desc:"A man in his 20s is conscious and talking. A piece of debris has penetrated his back close to the spine."},
  {id:"tp5d",pri:"P1",desc:"A woman in her 60s is unresponsive and not breathing. You open her airway and she begins to breathe again."},
  {id:"tp5e",pri:"P1",desc:"A man in his 40s is face down and unresponsive. He is not breathing until you open his airway, then shallow breaths return."},
  {id:"tp5f",pri:"P1",desc:"A teenage boy is unresponsive with no breathing. A head-tilt opens his airway and breathing resumes."},
  {id:"td6d",pri:"DEAD",desc:"A man in his 70s is supine and unresponsive. There is no response to shouting and no breathing once you have opened his airway."},
  {id:"td6e",pri:"DEAD",desc:"A woman in her 40s is lying still, with no response to voice or pain. You open her airway and there is no breathing and no movement."},
  {id:"td6f",pri:"DEAD",desc:"A man in his 50s is face down and unresponsive. After you open his airway there is no respiratory effort."},
  {id:"td6g",pri:"DEAD",desc:"An elderly man is motionless on the ground. You reposition his airway and there is still no breathing and no sign of life."},
  {id:"td6h",pri:"DEAD",desc:"A woman in her 30s is supine and unresponsive. Her airway is clear, but there is no breathing and no movement."},
  {id:"td6i",pri:"DEAD",desc:"A man in his 20s is lying completely still. There is no response to any stimulus and no breathing after his airway is opened."},
  {id:"td6j",pri:"DEAD",desc:"A woman in her 60s is unresponsive. After opening her airway there is no breathing and no movement at all."}
];
